spring.datasource.url=jdbc:mysql://localhost:3306/taskdb
spring.datasource.username=root
spring.datasource.password=0000
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=M2Q4ZjE5YzYxN2E0YjVlOWQzY2Y4MjE3NmI1YTA0YzhlZTY5ZjJkYjQxYzdhNWEzODQ2Y2QxZWI5ZjA3YQ==
jwt.expiration=86400000